server:
  port: 8000
spring:
  application:
    name: boot
  redis:
    port: 6379
    host: 127.0.0.1
    password: 123456
    database: 0
    timeout: 0
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
